name: Build and test with install script

on: [ push, pull_request ]

jobs:

  build-from-scratch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: init submodules
      run: git submodule init
    - name: update submodules
      run: git submodule update
    - name: Build from scratch
      run: sudo bash ./install.sh
